config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#index'
  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about
  root 'static_pages#home'
  
  resources :quizzes
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  get '/user/show' => 'users#show', as: :show_user
  get '/user/edit' => 'users#edit', as: :edit_user
  patch '/user/update' => 'users#update', as: :update_user

  get '/challenge_results', to: 'challenge_results#index'
  get '/challenge_results/setup', to: 'challenge_results#setup'
  get '/challenge_results/save_condition', to: 'challenge_results#save_condition'
  get '/challenge_results/start', to: 'challenge_results#next'
  get '/challenge_results/next', to: 'challenge_results#next'
  get '/challenge_results/challenge', to: 'challenge_results#challenge'
  post '/challenge_results/correct', to: 'challenge_results#correct'
  post '/challenge_results/uncorrect', to: 'challenge_results#uncorrect'
  
  resources :stars, only: [:create, :destroy]
end

app/models/challenge_result.rb
class ChallengeResult < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
end

app/controllers/challenge_results_controller.rb
class ChallengeResultsController < ApplicationController
  before_action :set_target_quizzes, only: [:setup, :next]
  
  def index
    @challenge_results = current_user.challenge_results
  end

  def setup

  end

  def save_condition
    session[:keyword] = params[:keyword]
    session[:tags] = params[:tags]
    session[:stared] = params[:stared]
    redirect_to action: :setup
  end
  
  def next
    target_quiz_ids = @quizzes.ids
    redirect_to challenge_results_setup_path and return if target_quiz_ids.blank?
    current_quiz_index = target_quiz_ids.index(params[:id].try(:to_i))
    next_quiz_id =  
      if current_quiz_index.nil? || current_quiz_index+1 == target_quiz_ids.size
        target_quiz_ids.first
      else
        target_quiz_ids[current_quiz_index+1]
      end

    next_quiz = Quiz.find next_quiz_id #target_quiz_ids.sample
    redirect_to challenge_results_challenge_path(id: next_quiz.id)
  end

  def challenge
    @quiz = Quiz.find params[:id]
  rescue => e
    logger.info e
    render_404 and return
  end

  def correct
    create(true)
  end
  
  def uncorrect
    create(false)
  end

  private
  
  
  def create(correct)
    @quiz = Quiz.find(params[:id])
    current_user.challenge_results.create(quiz: @quiz, correct: correct)
    redirect_to challenge_results_next_path(id: @quiz.id)
  end

  def set_target_quizzes
    @keyword = session[:keyword] 
    @tags = session[:tags]
    tag_array = @tags.try(:split, ',')
    @stared = session[:stared]
    @quizzes = Quiz.search(@keyword)
      .tap{|x| break x.tagged_with(tag_array) if tag_array.present? }
      .tap{|x| break x.joins(:stars).where(stars: {user_id: current_user.id}) if @stared }
      .order('quizzes.id')
  end

end

app/helpers/challenge_results_helper.rb
module ChallengeResultsHelper
end

app/views/challenge_results/challenge.html.erb
<%- model_class = Quiz -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="challenge_results">
  <div class="row">
    <div class="col-xs-1">No.</div>
    <div class="col-xs-11"><%= link_to @quiz.id, quiz_path(@quiz) %></div>
  </div>
  <div class="row">
    <div class="col-xs-1 question_label"><%= model_class.human_attribute_name(:question) %>:</div>
    <div class="col-xs-11">
      <div class="question"><%= markdown @quiz.question %></div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1"><%= model_class.human_attribute_name(:tag) %>:</div>
    <div class="col-xs-11">
      <% @quiz.tag_list.each do |tag| %>
      <span class="label label-info"><%= tag %></span>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-11">
      <span class="btn btn-default challenge_answer_show initial_show">show answer</span>
      <%= link_to '次の問題へ', challenge_results_next_path(id: @quiz.id), :class => 'btn btn-default initial_show'  %>
      <%= link_to '正解', challenge_results_correct_path(id: @quiz.id), method: :post, :class => 'btn btn-default initial_hide'  %>
      <%= link_to '不正解', challenge_results_uncorrect_path(id: @quiz.id), method: :post, :class => 'btn btn-default initial_hide'  %>
      <%= my_star @quiz %>
    </div>
  </div>
  <div class="challenge_answer initial_hide row">
    <div class="col-xs-1 answer_label"><%= model_class.human_attribute_name(:answer) %>:</div>
    <div class="col-xs-11">
      <div class="answer"><%= markdown @quiz.answer %></div>
    </div>
  </div>
  <div class="challenge_answer initial_hide row">
    <div class="col-xs-1 etc_label"><%= model_class.human_attribute_name(:etc) %>:</div>
    <div class="col-xs-11">
      <div class="etc"><%= markdown @quiz.etc %></div>
    </div>
  </div>
</div>

app/views/challenge_results/index.html.erb
<%- model_class = ChallengeResult -%>
<div>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% @challenge_results.order('id desc').each do |cr| %>
<div>
  <div class="quiz-row row">
    <div class="quiz col-md-4">
      <section>
        <h2><%= model_class.human_attribute_name(:question) %></h2>
        <div><%= markdown cr.quiz.question %></div>
      </section>
    </div>
    <div class="quiz col-md-4">
      <section>
        <h2><%= model_class.human_attribute_name(:correct) %></h2>
        <div><%= cr.correct %></div>
      </section>
    </div>
    <div class="quiz col-md-4">
      <section>
        <h2><%= model_class.human_attribute_name(:created_at) %></h2>
        <div><%= cr.created_at %></div>
      </section>
    </div>
  </div>
</div>
<hr>
<% end %>

app/views/challenge_results/setup.html.erb
<%- model_class = ChallengeResult -%>
<div>
  <h1>Set up</h1>
</div>
<div class="search-form panel panel-info">
  <div class="panel-body">
    <%= form_tag challenge_results_save_condition_path, method: :get, class: 'form-horizontal search_form' do %>
      <div class="row">
        <div class="col-md-6">
          <div class="row form-group form-group-sm">
            <label class="col-md-3 control-label">キーワード</label>
            <div class="col-md-9">
              <%= search_field_tag :keyword, @keyword, class: "form-control input-sm", placeholder: 'キーワード' %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row form-group form-group-sm">
            <label class="col-md-4 control-label">お気に入り</label>
            <div class="col-md-8">
              <div data-toggle="buttons" class="star-btn">
                <label class="btn btn-default<%= ' active' if @stared %>">
                  <%= check_box_tag :stared, @stared, @stared, class: "checkbox-inline" %>
                  <i class="fa fa-star" style="color:gold;"></i>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="row form-group form-group-sm">
            <label class="col-md-3 control-label">タグ</label>
            <div class="col-md-9">
              <%= text_field_tag :tags, @tags, id: "quiz_tag_list", data: {role: "tagsinput"} ,class: "form-control input-sm" %>
              <span class="fa fa-times tags_remove_all"></span>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row most_used_tags form-group form-group-sm">
            <label class="col-md-4 control-label">よく使われているタグ</label>
            <div class="col-md-8">
            <% ActsAsTaggableOn::Tag.most_used(20).each do |t| %>
              <span class="tag label label-info"><%= t.name %></span>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      <%= submit_tag '条件を保存', name: nil, class: "btn btn-info form-control" %>
    <% end %>
  </div>
</div>
<p>対象のクイズは<%= @quizzes.count %>件あります。</p>
<%= link_to 'Start', challenge_results_start_path, class: 'btn btn-primary' %>