config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#index'
  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about
  root 'static_pages#home'
  
  resources :quizzes
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  get '/user/show' => 'users#show', as: :show_user
  get '/user/edit' => 'users#edit', as: :edit_user
  patch '/user/update' => 'users#update', as: :update_user

  get '/challenge_results', to: 'challenge_results#index'
  get '/challenge_results/setup', to: 'challenge_results#setup'
  get '/challenge_results/save_condition', to: 'challenge_results#save_condition'
  get '/challenge_results/start', to: 'challenge_results#next'
  get '/challenge_results/next', to: 'challenge_results#next'
  get '/challenge_results/challenge', to: 'challenge_results#challenge'
  post '/challenge_results/correct', to: 'challenge_results#correct'
  post '/challenge_results/uncorrect', to: 'challenge_results#uncorrect'
  
  resources :stars, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable
  before_create :set_default_nickname
  validates :nickname, presence: true, on: :update
  validates :email, email: {allow_blank: true}, on: :update
  has_many :challenge_results
  has_many :quizzes

  private
  
  def set_default_nickname
    self.nickname = "no_name"
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.find_or_create_by(user_params)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  private
  def user_params
    request.env["omniauth.auth"].slice(:provider, :uid).to_h
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user
  
    def show
        
    end
    
    def edit
        
    end
    
    def update
      if @user.update(user_params)
        redirect_to show_user_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
    
    private
    
    def set_user
        @user = current_user
    end

    def user_params
      params.require(:user).permit(:nickname, :email)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @user, url: update_user_path, :html => { :class => "form-horizontal" } do |f| %>
    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this quiz from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :nickname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nickname, :class => 'form-control' %>
    </div>
    <%#= error_span(@user[:nickname]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%#= error_span(@user[:email]) %>
  </div>

  <p class="user_actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            show_user_path, :class => 'btn btn-default' %>
  </p>
<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nickname) %>:</strong></dt>
  <dd><%= @user.nickname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>
<p class="quiz_actions">
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path, :class => 'btn btn-default' %>
</p>