config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#index'
  get 'home' => 'static_pages#home', as: :home
  get 'about' => 'static_pages#about', as: :about
  root 'static_pages#home'
  
  resources :quizzes
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  get '/user/show' => 'users#show', as: :show_user
  get '/user/edit' => 'users#edit', as: :edit_user
  patch '/user/update' => 'users#update', as: :update_user

  get '/challenge_results', to: 'challenge_results#index'
  get '/challenge_results/setup', to: 'challenge_results#setup'
  get '/challenge_results/save_condition', to: 'challenge_results#save_condition'
  get '/challenge_results/start', to: 'challenge_results#next'
  get '/challenge_results/next', to: 'challenge_results#next'
  get '/challenge_results/challenge', to: 'challenge_results#challenge'
  post '/challenge_results/correct', to: 'challenge_results#correct'
  post '/challenge_results/uncorrect', to: 'challenge_results#uncorrect'
  
  resources :stars, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studyapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
<%= nav_bar fixed: :top, brand: "StudyApp", responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "About", about_path %>
        <% if user_signed_in? %>
          <%= drop_down "Quiz" do %>
            <%= menu_item "Quiz List", quizzes_path %>
            <%= menu_item "Toggle Answer", 'javascript:void(0);', class: :toggle_answer %>
          <% end %>
          <%= drop_down "Challenge" do %>
            <%= menu_item "Setup", challenge_results_setup_path %>
            <%= menu_item "Challenge Results", challenge_results_path %>
          <% end %>
          <%= drop_down "User" do %>
            <%= menu_item "Show User", show_user_path %>
            <%= menu_item "Sign out", destroy_user_session_path %>
          <% end %>
        <% else %>
          <%= menu_item "Sign in with Twitter", user_twitter_omniauth_authorize_path %>
        <% end %>
    <% end %>
    <%= menu_group pull: :right do %>
    <% end %>
<% end %>

<div class="container main">
  <% flash.each do |key, value| %>
  <% type = case key
       when "notice" then "success"
       when "danger" then "alert"
       else "info"
       end %>
  <div class="alert alert-dismissible alert-<%= type %>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= value %>
  </div>
  <%#= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <div>
    <%= yield %>
  </div>
</div>
</body>
</html>